# Generated by Django 5.0.7 on 2024-08-02 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='collection_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nft',
            name='blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.blockchain'),
        ),
        migrations.AddField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='nfts',
            field=models.ManyToManyField(blank=True, related_name='collections', to='collection.nft'),
        ),
        migrations.AddField(
            model_name='auctionnft',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.nft'),
        ),
    ]
