# Generated by Django 5.0.7 on 2024-08-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='followers',
        ),
    ]
